baseURL = "http://learn.greyhatctf.com"
languageCode = "en-us"
title = "GreyHat CTF Educational Content"
SectionPagesMenu = "main"

[[menu.main]]
  name = "defense"
  url  = "/defense/"
  weight = 900

[[menu.main]]
  name = "attack"
  url  = "/attack/"
  weight = 900

[params]
  noCategoryLink = true
  description = "Learn through Capture the Flag"


